### ISSUE TITLE
update shiki version to 0.1.6

### ISSUE THREAD

**Issue by swyxio** [rsclarke/rehype-shiki#2]
hi! i recently asked for and got this language addition: https://github.com/octref/shiki/issues/20#event-2647732167

and now i need it to be added to rehype-shiki so i can actually use it 😅

do you mind updating?

**Comment by rsclarke** [comment]
Upgraded dependencies in commit 93d78d7 and released v0.0.5.

**Comment by swyxio** [comment]
awesome! thank you and thank you for this library, im using it happily for swyx.io!
