### ISSUE TITLE
useBackground option does not work

### ISSUE THREAD

**Issue by marekweb** [rsclarke/rehype-shiki#26]
I found a small issue with the the way the plugin handles the options.

**Steps to reproduce:**

Attach the plugin, provide `{useBackground: false}` as the options, and run it on some HTML with a code block.

**Expected behavior:**

The plugin does not set a background color on the `pre` tag.

**Actual behavior:**

The plugin ignores the options and sets a background color on the `pre` tag

**Comment by ng-hai** [comment]
I recently run into this bug, and it breaks on production only after bumping to v0.0.7.

The occurrence error is:

`CSS2Properties doesn't have an indexed property setter for '0'`

Similar to this issue: https://github.com/facebook/react/issues/15375

Hope this PR will be merge soon!

**Comment by rsclarke** [comment]
Apologies for the delay on this, merged and released in 0.0.8.  Hope this resolves the issues you are facing.

**Comment by ng-hai** [comment]
Thank @rsclarke for your great work.
